# Use an official Node.js runtime as a base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app/server

# Copy package.json and package-lock.json to the working directory
COPY server/package*.json ./


# Install dependencies

RUN npm install

# Copy the local code to the container
COPY server/ .

# Expose the backend server port
EXPOSE 8081

# Command to run the backend server
CMD ["npm", "start"]