version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"