# Use an official MongoDB image as a base image
FROM mongo:latest

# Expose MongoDB port
EXPOSE 27017

# Optional: Set environment variables for MongoDB configuration
ENV MONGO_INITDB_ROOT_USERNAME=test0db
ENV MONGO_INITDB_ROOT_PASSWORD=test123